#!/bin/bash

tput civis

# Colours
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0m"
redColour="\e[0;31m\033[1m"
blueColour="\e[0;34m\033[1m"
yellowColour="\e[0;33m\033[1m"
purpleColour="\e[0;35m\033[1m"
turquoiseColour="\e[0;36m\033[1m"
grayColour="\e[0;37m\033[1m"

function ctrl_c() {
  echo -e "\n\n${redColour}[!] Saliendo...${endColour}\n"
  tput cnorm && exit 1
}

# Ctrl+C
trap ctrl_c INT

rofi_install(){
  echo -e "${blueColour}[*] Instalando rofi...${endColour}"
  sudo cp rofi /usr/bin/rofi
  if [ ! -d "/usr/local/rofi" ]; then
    sudo mkdir -p /usr/local/rofi/themes
    sudo cp -r rofi_themes/* /usr/local/rofi/themes/
  else
    sudo cp -r rofi_themes/* /usr/local/rofi/themes/
  fi

  if [ ! -d "/usr/share/rofi" ]; then
    sudo mkdir -p /usr/share/rofi/themes
    sudo cp -r rofi_themes/* /usr/share/rofi/themes/
  else
    sudo cp -r rofi_themes/* /usr/share/rofi/themes/
  fi
}

rofi_install

tput cnorm 

